version: "3.8"

services: 
  frontend: 
    image: akhil1994/akn-frontend
    ports: 
      - "80:80"
      - "443:443"
    networks:
      - frontend
    volumes:
      - /home/opc/certs:/app/certs
    deploy:
      replicas: 1

  backend:
    image: akhil1994/akn-backend
    environment:
      SPRING.DATASOURCE.URL: jdbc:postgresql://db:5432/akn-db?user=postgres&password=postgres
    networks:
      - frontend
      - backend
    deploy:
      replicas: 1
    depends_on:
      - db
  
  db:
    image: postgres:9.4
    environment: 
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "akn-db"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - backend
    deploy:
      replicas: 1
      placement: 
        constraints:
          - "node.labels.region==instance2"
  
networks:
  frontend:
  backend:

volumes:
  db-data: