version: "3.8"

services: 
  akn-frontend: 
    image: akhil1994/akn-frontend
    ports: 
      - "80:80"
    networks:
      - frontend
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  akn-backend:
    image: akhil1994/akn-backend
    ports:
      - "8080:8080"
    environment:
      SPRING.DATASOURCE.URL: jdbc:postgresql://db:5432/akn-db?user=postgres&password=postgres
    networks:
      - backend
    deploy:
      replicas: 1
    depends-on:
      - db
  
  db:
    image: postgres:9.4
    environment: 
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "akn-db"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - backend
  
networks:
  frontend:
  backend:

volumes:
  db-data: